sudo: required

services:
  - docker

before_install:
  - docker build -t frenzymadness/fedora-python-tox .
  - docker images

script:
  # Test project in local folder mounted as a volume into Docker container
  - cd example_project && docker run --rm -it -v $PWD:/src -w /src -e TOXENV frenzymadness/fedora-python-tox
  # Test project cloned into Docker container from provided GIT URL
  - docker run --rm -it -e TOXENV -e GIT_URL=https://github.com/frenzymadness/python-tox-example.git frenzymadness/fedora-python-tox

matrix:
  include:
  - env: TOXENV=py27
  - env: TOXENV=py34
  - env: TOXENV=py35
  - env: TOXENV=py36
  - env: TOXENV=py37
  - env: TOXENV=pypy
  - env: TOXENV=pypy3
  - env: TOXENV=jython
  allow_failures:
  - env: TOXENV=jython  # https://github.com/tox-dev/tox/issues/782
