sudo: required

services:
  - docker

before_install:
  - docker build -t frenzymadness/fedora-python-tox .
  - docker images

script:
  - cd example_project && docker run --rm -it -v $PWD:/src -w /src frenzymadness/fedora-python-tox
